import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";
import type { ReportData } from "@/lib/reports";

const BRAND: [number, number, number] = [99, 91, 255];

/** Build and download a PDF for a generated report (client-side). */
export function downloadReportPdf(data: ReportData & { id?: string }) {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 40;
  let y = 54;

  // Header band
  doc.setFillColor(...BRAND);
  doc.rect(0, 0, pageWidth, 8, "F");

  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.setTextColor(20, 20, 30);
  doc.text(data.title, margin, y);
  y += 20;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(120, 120, 130);
  const period = `${new Date(data.period.start).toLocaleDateString()} – ${new Date(data.period.end).toLocaleDateString()}  ·  ${data.type} report  ·  Generated ${new Date(data.generatedAt).toLocaleString()}`;
  doc.text(period, margin, y);
  y += 24;

  const section = (title: string) => {
    if (y > 740) {
      doc.addPage();
      y = 54;
    }
    doc.setFont("helvetica", "bold");
    doc.setFontSize(13);
    doc.setTextColor(...BRAND);
    doc.text(title, margin, y);
    y += 16;
    doc.setTextColor(40, 40, 50);
  };

  const paragraph = (text: string) => {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(60, 60, 70);
    const lines = doc.splitTextToSize(text, pageWidth - margin * 2);
    if (y + lines.length * 13 > 780) {
      doc.addPage();
      y = 54;
    }
    doc.text(lines, margin, y);
    y += lines.length * 13 + 10;
  };

  section("Executive summary");
  paragraph(data.executiveSummary);

  section("Key metrics");
  autoTable(doc, {
    startY: y,
    head: [["Metric", "Value"]],
    body: [
      ["Total mentions", String(data.totals.total)],
      ["Positive", String(data.totals.positive)],
      ["Neutral", String(data.totals.neutral)],
      ["Negative", String(data.totals.negative)],
      ["Net sentiment", String(data.totals.netSentiment)],
      ["High/critical risk", String(data.totals.highRisk)],
      ["Estimated total reach", data.totals.totalReach.toLocaleString()],
    ],
    theme: "striped",
    headStyles: { fillColor: BRAND },
    margin: { left: margin, right: margin },
  });
  y = (doc as any).lastAutoTable.finalY + 20;

  section("Top publications");
  autoTable(doc, {
    startY: y,
    head: [["Publication", "Mentions", "Est. reach"]],
    body: data.topPublications.map((p) => [p.name, String(p.count), p.reach.toLocaleString()]),
    theme: "striped",
    headStyles: { fillColor: BRAND },
    margin: { left: margin, right: margin },
  });
  y = (doc as any).lastAutoTable.finalY + 20;

  section("Top journalists");
  autoTable(doc, {
    startY: y,
    head: [["Journalist", "Mentions"]],
    body: data.topJournalists.length ? data.topJournalists.map((j) => [j.name, String(j.count)]) : [["No attributed authors", "—"]],
    theme: "striped",
    headStyles: { fillColor: BRAND },
    margin: { left: margin, right: margin },
  });
  y = (doc as any).lastAutoTable.finalY + 20;

  section("Top topics");
  autoTable(doc, {
    startY: y,
    head: [["Topic", "Mentions"]],
    body: data.topTopics.map((t) => [t.topic, String(t.count)]),
    theme: "striped",
    headStyles: { fillColor: BRAND },
    margin: { left: margin, right: margin },
  });
  y = (doc as any).lastAutoTable.finalY + 20;

  section("AI commentary");
  paragraph(data.aiCommentary);

  section("Recommendations");
  data.recommendations.forEach((r, i) => paragraph(`${i + 1}. ${r}`));

  // Footer on every page
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 160);
    doc.text("Generated by MediaPulse AI", margin, doc.internal.pageSize.getHeight() - 20);
    doc.text(`Page ${i} of ${pageCount}`, pageWidth - margin - 60, doc.internal.pageSize.getHeight() - 20);
  }

  doc.save(`${data.title.replace(/[^a-z0-9]+/gi, "-").toLowerCase()}.pdf`);
}
